In [ ]:
# Random numbers Matrix multlipication

import random   # importing an inbuilt function to generate random numbers
import numpy as n # numpy helps to generate a random number between 0-1

r=3 # number of rows
c=3 # number of colums


m1=[[0 for _ in range(r)]for _ in range(c)]

for i in range(3):
  for j in range(3):
    a=random.randint(-999,999)
    m1[i][j]=a
  
print("\nmatrix m1 =")
for x in m1:
  print(x)
print("\n\n")


m2=[[0 for _ in range(r)]for _ in range(c)]

for i in range(3):
  for j in range(3):
    b=random.randint(-999,999)
    m2[i][j]=b

print("\nmatrix m2 =")
for x in m2:
  print(x)
print("\n\n")


ma=[[0 for _ in range(r)]for _ in range(c)]

# multiply
ma = n.dot(m1,m2)

print("\n Multiplied matrix ma =")
print(ma)


matrix m1 =
[769, -259, -903]
[252, -781, -607]
[742, -97, 44]




matrix m2 =
[-729, -838, -818]
[638, 269, -722]
[270, -410, 811]




 Multiplied matrix ma =
[[ -969653  -343863 -1174377]
 [ -845876  -172395  -134531]
 [ -590924  -665929  -501238]]
